# Generated by Django 5.1.6 on 2025-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrefund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
